- name: Creating Developer Environment
  hosts: localhost

  tasks:
    - name: Update Homebrew
      homebrew:
        update_homebrew: yes

    - name: Install additional dependencies
      become: false
      homebrew:
        name:
          - gnupg
          - fzf
          - jq
          - neovim
          - shellcheck
          - stow
          - curl
          - openssl@1.1
          - lua-language-server
          - ack
          - gh
          - ansible-lint
          - stylua
          - notion
          - ultimaker-cura
          - tmux
          - tmuxinator
          - lazygit
          - dotnet-sdk
          - omnisharp
          - omnisharp-mono

        state: present

    - name: Install Vim-Plug for Neovim
      # become: true
      ansible.builtin.shell: >
        curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    - name: Install Jedi package using pip
      pip:
        name: jedi
        state: present

    - name: Install ansible-lint using pip
      pip:
        name: ansible-lint
        state: present
