- name: Download zsh
  hosts: localhost
  become: true
  environment:
  tasks:
    - name: Stow dotfiles
      shell: |
        cd {{ playbook_dir }}/../../../config && ./install.sh
      become: true
