version: "3.1"

services:
  ansible:
    container_name: ansible
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./playbooks:/playbooks
volumes:
  datavolume:
