- name: Creating Developer Enviroment
  hosts: localhost
  become: true

  tasks:
    - name: Install geeneric CLIS
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Install Doppler CLI on Ubuntu
      become: yes
      apt:
        name: doppler
        state: present

    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Doppler CLI
      apt:
        name:
          - doppler
        state: present

    - name: Install vim and tmux
      apt:
        name:
          - vim
          - tmux
        state: present

    - name: Install packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd62] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Add Node.js GPG key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add Node.js repository
      apt_repository:
        repo: deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main
        state: present
      vars:
        nodejs_version: 14

    - name: Install Node.js and Yarn
      apt:
        name:
          - nodejs
          - yarn
        state: present

    - name: Install additional dependencies
      apt:
        name:
          - build-essential
          - libssl-dev
          - python3-dev
          - python3-pip
          - python3-venv
        state: present

    - name: Install Git
      apt:
        name:
          - git
        state: present
