- hosts: localhost
  tasks:
    - name: Load variables from .env file
      ansible.builtin.include_vars:
        file: .env

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Authenticate with GitHub
      community.general.github_repository:
        username: "{{ github_user }}"
        password: "{{ github_token }}"
        repository: "{{ repository_name }}"
        owner: "{{ repository_owner }}"
        action: get
      register: github_auth_result

    - name: Cache GitHub credentials
      command: git config --global credential.helper cache
