- name: Creating Developer Enviroment
  hosts: localhost
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install additional dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
          - build-essential
          - libssl-dev
          - python3-dev
          - python3-pip
          - python3-venv
          - stow
          - fzf
          - jq
          - shellcheck
          - neovim
          - exuberant-ctags
          - gh
          - wget
          - gpg
          - notion
          - steam
          - tmux
          - tmuxinator

        state: present

    - name: Install Vim-Plug for Neovim
      become: true
      ansible.builtin.shell: >
        curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    - name: Install Jedi package using pip
      pip:
        name: jedi
        state: present
