- name: Creating Developer Enviroment
  hosts: localhost
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install generics CLIS
      apt:
        name:

        state: present

    - name: Install additional dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
          - build-essential
          - libssl-dev
          - python3-dev
          - python3-pip
          - python3-venv
          - stow
        state: present
