---
- name: Install nvm and latest version of Node.js
  hosts: localhost
  become: true
  tasks:
    - name: Install nvm
      git:
        repo: https://github.com/creationix/nvm.git
        dest: ~/.nvm
        version: v0.33.11
      tags: nvm

    - name: Source nvm in ~/.{{ item }}
      lineinfile:
        dest: "~/.{{ item }}"
        line: "source ~/.nvm/nvm.sh"
        create: yes
      tags: nvm
      with_items:
        - bashrc
        - profile

    - name: Install latest version of Node.js
      shell: |
        source ~/.nvm/nvm.sh
        nvm install --lts
      args:
        executable: /bin/bash

    - name: Add Yarn GPG key
      shell: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      
    - name: Add Yarn repository to sources.list
      shell: echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install Yarn
      apt:
        name: yarn
        state: latest
