- name: Download zsh
  hosts: localhost
  become: true
  environment:
    HOME: "/home/martin"
  tasks:
    - name: Install Zsh package
      apt:
        name: zsh
        state: present

    - name: Set default shell to Zsh for current user
      shell: chsh -s $(which zsh) $USER

    - name: change user shell to zsh
      become: yes
      user:
        name: "martin"
        shell: /usr/bin/zsh
