- name: Install Hacker Font
  hosts: localhost
  become: true

  tasks:
    - name: ensure fonts directory
      file:
        path: "../../config/home/.fonts"
        state: directory

    - name: Hack exists
      shell: "ls ../../config/home/.fonts/Hack*Nerd*Font*Complete*"
      register: hack_exists
      ignore_errors: yes

    - name: Download Hack
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
        dest: "../../config/home/.fonts"
        remote_src: yes