name: CreadorDeAlarmas
root: ~/Projects/CreadorDeAlarmas
windows:
  - gits:
      layout: even-horizontal
      panes:
        - cd CreadorDeAlarmas && lazygit
        - cd CreadorDeAlarmasWP && lazygit
  - back:
      root: ~/Projects/CreadorDeAlarmas/CreadorDeAlarmas
      layout: even-horizontal
      panes:
        - nvim .
        - yarn docker:dev
  - whatsapp:
      root: ~/Projects/CreadorDeAlarmas/CreadorDeAlarmasWP
      layout: even-horizontal
      panes:
        - nvim .
        - yarn start
