name: Dictados 
root: ~/Projects/Dictados/DA1/02-2024

windows:
  - M4B:
      root: ~/Projects/Dictados/DA1/02-2024/M4B-AN/M4B-AN-TEC-02.2024
      layout: even-horizontal
      panes:
        - nvim .
        - .
  - M4A:
      root: ~/Projects/Dictados/DA1/02-2024/M4A-AN/M4A-AN-Tec
      layout: even-horizontal
      panes:
        - nvim .
        - .
