# /Users/maritnradovitzky/.config/tmuxinator/dotfiles.yml
name: dotfiles
root: ~/Documents/PersonalProjects/ansible-scripts
# on_project_start: docker-compose up -d
windows:
  - git:
      panes:
        - lazygit
  - config:
      layout: even-horizontal
      panes:
        - cd config && nvim
        - cd config
  - playbooks:
      layout: even-horizontal
      panes:
        - cd playbooks && nvim
        - cd playbooks
  - root:
      layout: even-horizontal
      panes:
        - nvim .
        - cd .
