# /Users/maritnradovitzky/.config/tmuxinator/dotfiles.yml
name: dotfiles
root: ~/Documents/PersonalProjects/ansible-scripts
# on_project_start: docker-compose up -d
windows:
  - git:
      panes:
        - lazygit
  - root:
      layout: even-horizontal
      panes:
        - nvim .
        - cd .
  - config:
      layout: even-horizontal
      panes:
        - cd config && nvim
        - cd config
  - tmuxinator:
      layout: even-horizontal
      panes:
        - cd config/.config/tmuxinator && nvim
        - cd config/.config/tmuxinator
  - playbooks:
      layout: even-horizontal
      panes:
        - cd playbooks && nvim
        - cd playbooks
