name: elpechudo
root: ~/Projects/elpechudo
windows:
  - front:
      layout: even-horizontal
      panes:
        - nvim front
        - cd front && yarn start
  - back:
      layout: even-horizontal
      panes:
        - nvim back
        - cd back && yarn docker:dev
  - gits:
    layout: even-horizontal
    panes:
      - cd back
      - cd front
