name: elpechudo
root: ~/Projects/elpechudo
windows:
  - front:
      layout: even-horizontal
      panes:
        - cd front && nvim
        - cd front && yarn start
  - back:
      layout: even-horizontal
      panes:
        - cd back && nvim .
        - cd back && yarn docker:dev
  - gits:
    layout: even-horizontal
    panes:
      - cd front && lazygit
      - cd back && lazygit
