name: elpechudo
root: ~/Projects/elpechudo
windows:
  - gits:
      layout: even-horizontal
      panes:
        - cd front && lazygit
        - cd back && lazygit
  - front:
      root: ~/Projects/elpechudo/front
      layout: even-horizontal
      panes:
        - nvim
        - yarn start
  - back:
      root: ~/Projects/elpechudo/back
      layout: even-horizontal
      panes:
        - nvim .
        - yarn docker:dev
