
# /Users/maritnradovitzky/.config/tmuxinator/dotfiles.yml
name: liveonitDotfiles
root: ~/Documents/PersonalProjects/liveonit/dotfiles
# on_project_start: docker-compose up -d
windows:
  - config:
      layout: even-horizontal
      panes:
        - nvim .dotfiles
        - cd .dotfiles
  - playbooks:
      layout: even-horizontal
      panes:
        - nvim ansible 
        - cd ansible
  - root:
      layout: even-horizontal
      panes:
        - cd ~
