# /Users/maritnradovitzky/.config/tmuxinator/dotfiles.yml
name: notes
root: ~/Notes
# on_project_start: docker-compose up -d
windows:
  - notes:
      layout: even-horizontal
      panes:
        - nvim .
        -
