name: OptiTask
root: ~/Projects/OptiTask/
windows:
  - gits:
      root: ~/Projects/OptiTask
      layout: main-vertical
      panes:
        - cd Backend && lazygit
        - cd Web && lazygit
        - cd Mobile && lazygit
  - web:
      root: ~/Projects/OptiTask/Web
      layout: main-vertical
      panes:
        - nvim .
        - yarn dev
        - .
  - back:
      root: ~/Projects/OptiTask/Backend
      layout: main-vertical
      panes:
        - nvim .
        - yarn docker:dev
        - .
  - mobile:
      root: ~/Projects/OptiTask/Mobile
      layout: main-vertical
      panes:
        - nvim .
        - yarn dev
        - .
