name: qualityService
root: ~/Projects/QualityService/
windows:
  - gits:
      root: ~/Projects/QualityService
      layout: main-vertical
      main-pane-width: 50%
      panes:
        - backend:
            - cd cleanup-backend && lazygit
        - web:
            - cd cleanup-dashboard  && lazygit
        - three:
            - cd cleanup-mobile && lazygit
  - web:
      root: ~/Projects/QualityService/cleanup-dashboard
      layout: even-horizontal
      panes:
        - nvim .
        - .
  - back:
      root: ~/Projects/QualityService/cleanup-backend
      layout: even-horizontal
      panes:
        - nvim .
        - .
  - web:
      root: ~/Projects/QualityService/cleanup-mobile
      layout: even-horizontal
      panes:
        - nvim .
        - .
