name: qualityService
root: ~/Projects/QualityService/
windows:
  - gits:
      root: ~/Projects/QualityService
      layout: even-horizontal
      panes:
        - cd cleanup-backend && lazygit
        - cd infra && lazygit
  - web:
      root: ~/Projects/QualityService/cleanup-dashboard
      layout: even-horizontal
      panes:
        - nvim .
        - .
  - back:
      root: ~/Projects/QualityService/cleanup-backend
      layout: even-horizontal
      panes:
        - nvim .
        - .
  - mobile:
      root: ~/Projects/QualityService/cleanup-mobile
      layout: even-horizontal
      panes:
        - nvim .
        - .
  - infra:
      root: ~/Projects/QualityService/infra
      layout: even-horizontal
      panes:
        - nvim .
        - .
