# /Users/maritnradovitzky/.config/tmuxinator/stride.yml
name: stride
root: ~/Documents/December/Stride/stride-origin
# on_project_start: docker-compose up -d
windows:
  - git:
      panes:
        - lazygit
  - root:
      layout: even-horizontal
      panes:
        - nvim
        -
  - web:
      layout: even-horizontal
      root: ~/Documents/December/Stride/stride-origin/web
      panes:
        - nvim
        -
  - firebase:
      layout: even-horizontal
      root: ~/Documents/December/Stride/stride-origin/firebase
      panes:
        - nvim
        -
  - cloudFunc:
      layout: even-horizontal
      panes:
        - cd functions && nvim
        - source .venv/bin/activate && cd functions
  - admin:
      layout: even-horizontal
      root: ~/Documents/December/Stride/stride-origin/stride-origin-admin
      panes:
        - nvim
        -
  - devops:
      layout: even-horizontal
      root: ~/Documents/December/Stride/stride-origin/devops
      panes:
        - nvim
        -
