- name: Install utils Apps
  hosts: localhost
  become: true

  tasks:
    - name: Download Google Chrome DEB file
      shell: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      args:
        chdir: /tmp

    - name: Install Google Chrome using dpkg
      shell: |
        sudo dpkg -i google-chrome-stable_current_amd64.deb
      args:
        chdir: /tmp

    - name: Install Discord
      apt:
        deb: https://discord.com/api/download?platform=linux&format=deb
        state: present

    - name: Install Slack dependencies
      apt:
        name:
          - libgtk-3-0
          - libnotify4
          - libnss3
          - libxss1
          - libxtst6
          - xdg-utils
        state: present

    - name: Download Slack package
      get_url:
        url: https://downloads.slack-edge.com/linux_releases/slack-desktop-4.17.0-amd64.deb
        dest: /tmp/slack-desktop.deb

    - name: Install Slack
      apt:
        deb: /tmp/slack-desktop.deb
        state: present

    - name: Download Zoom package
      get_url:
        url: https://zoom.us/client/latest/zoom_amd64.deb
        dest: /tmp/zoom.deb

    - name: Install Zoom
      apt:
        deb: /tmp/zoom.deb
        state: present
