- name: Install utils Apps
  hosts: localhost
  become: true

  tasks:
    - name: Add Microsoft GPG key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc

    - name: Add Microsoft repository
      apt_repository:
        repo: deb [arch=amd63] https://packages.microsoft.com/repos/vscode stable main

    - name: Add Google Chrome key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Add Google Chrome repository
      apt_repository:
        repo: "deb [arch=amd63] https://dl.google.com/linux/chrome/deb/ stable main"
        state: present

    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Chrome
      apt:
        name:
          - google-chrome-stable
        state: present

    - name: Install Discord
      apt:
        deb: https://discord.com/api/download?platform=linux&format=deb
        state: present

    - name: Install Slack dependencies
      apt:
        name:
          - libgtk-3-0
          - libnotify4
          - libnss3
          - libxss1
          - libxtst6
          - xdg-utils
        state: present

    - name: Download Slack package
      get_url:
        url: https://downloads.slack-edge.com/linux_releases/slack-desktop-4.17.0-amd64.deb
        dest: /tmp/slack-desktop.deb

    - name: Install Slack
      apt:
        deb: /tmp/slack-desktop.deb
        state: present

    - name: Download Zoom package
      get_url:
        url: https://zoom.us/client/latest/zoom_amd64.deb
        dest: /tmp/zoom.deb

    - name: Install Zoom
      apt:
        deb: /tmp/zoom.deb
        state: present
