---
- name: Install Docker, Node.js, Yarn, VS Code, Chrome, Discord, Slack, DataGrip, and dependencies
  hosts: localhost
  become: true

  vars:
    toolbox_version: 1.17.7391
    toolbox_filename: jetbrains-toolbox-{{ toolbox_version }}.tar.gz
    toolbox_download_url: https://download.jetbrains.com/toolbox/{{ toolbox_filename }}
    toolbox_install_dir: /opt/jetbrains-toolbox

  tasks:
    - name: Add Microsoft GPG key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc

    - name: Add Microsoft repository
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main

    - name: Install Doppler CLI
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Add Doppler GPG key
      apt_key:
        url: https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key

    - name: Add Doppler package repository
      apt_repository:
        repo: "deb https://packages.doppler.com/public/cli/deb/debian any-version main"
        state: present

    - name: Add Google Chrome key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Add Google Chrome repository
      apt_repository:
        repo: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
        state: present

    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Doppler CLI
      apt:
        name:
          - doppler
        state: present

    - name: Install VS Code
      apt:
        name:
          - code
        state: present

    - name: Install packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Add Node.js GPG key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add Node.js repository
      apt_repository:
        repo: deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main
        state: present
      vars:
        nodejs_version: 16

    - name: Install Node.js and Yarn
      apt:
        name:
          - nodejs
          - yarn
        state: present

    - name: Install Chrome
      apt:
        name:
          - google-chrome-stable
        state: present

    - name: Install Discord
      apt:
        deb: https://discord.com/api/download?platform=linux&format=deb
        state: present

    - name: Install Slack
      apt:
        deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-4.16.0-amd64.deb
        state: present

    - name: Download JetBrains Toolbox App tarball
      get_url:
        url: "{{ toolbox_download_url }}"
        dest: "{{ toolbox_filename }}"

    - name: Extract JetBrains Toolbox App to {{ toolbox_install_dir }}
      unarchive:
        src: "{{ toolbox_filename }}"
        dest: "{{ toolbox_install_dir }}"
        remote_src: true
        creates: "{{ toolbox_install_dir }}/jetbrains-toolbox-{{ toolbox_version }}/jetbrains-toolbox"

    - name: Run JetBrains Toolbox App
      shell: "{{ toolbox_install_dir }}/jetbrains-toolbox-{{ toolbox_version }}/jetbrains-toolbox"

    - name: Install additional dependencies
      apt:
        name:
          - build-essential
          - libssl-dev
          - python3-dev
          - python3-pip
          - python3-venv
        state: present
